
// create routing matrices for the Floyd-Warshall algorithm, given a list of node IDs and edges
export function createRoutingMatrices(nodeIds, edges) {
  if (!Array.isArray(nodeIds) || nodeIds.length === 0) {
    throw new TypeError("Routing nodes must be a non-empty array");
  }
  if (!Array.isArray(edges)) {
    throw new TypeError("Routing edges must be an array");
  }

  const indexByNodeId = new Map();
  nodeIds.forEach((nodeId, index) => {
    if (typeof nodeId !== "string" || nodeId.length === 0) {
      throw new TypeError("Each routing node must have a non-empty string ID");
    }
    if (indexByNodeId.has(nodeId)) {
      throw new TypeError(`Duplicate routing node: ${nodeId}`);
    }
    indexByNodeId.set(nodeId, index);
  });

  const distances = Array.from(
    { length: nodeIds.length },
    () => Array(nodeIds.length).fill(Infinity),
  );
  const next = Array.from(
    { length: nodeIds.length },
    () => Array(nodeIds.length).fill(null),
  );

  nodeIds.forEach((_nodeId, index) => {
    distances[index][index] = 0;
    next[index][index] = index;
  });

  edges.forEach((edge) => {
    const fromIndex = indexByNodeId.get(edge.from);
    const toIndex = indexByNodeId.get(edge.to);

    if (fromIndex === undefined || toIndex === undefined) {
      throw new TypeError(`Route edge contains an unknown node: ${edge.from}-${edge.to}`);
    }
    if (fromIndex === toIndex) {
      throw new TypeError(`Route edge cannot connect a node to itself: ${edge.from}`);
    }
    if (!Number.isFinite(edge.weight) || edge.weight <= 0) {
      throw new TypeError(`Route edge weight must be positive: ${edge.from}-${edge.to}`);
    }

    // if there are multiple edges between the same pair of nodes, we keep the one with the smallest weight
    if (edge.weight < distances[fromIndex][toIndex]) {
      distances[fromIndex][toIndex] = edge.weight;
      distances[toIndex][fromIndex] = edge.weight;
      next[fromIndex][toIndex] = toIndex;
      next[toIndex][fromIndex] = fromIndex;
    }
  });

  return {
    nodeIds: [...nodeIds],
    indexByNodeId,
    distances,
    next,
  };
}

// returns the cost of the shortest route between two nodes, given the routing matrices
export function floydWarshall(nodeIds, edges) {
  const matrices = createRoutingMatrices(nodeIds, edges);
  const { distances, next } = matrices;

  for (let via = 0; via < nodeIds.length; via += 1) {
    for (let from = 0; from < nodeIds.length; from += 1) {
      if (distances[from][via] === Infinity) continue;

      for (let to = 0; to < nodeIds.length; to += 1) {
        const distanceThroughVia = distances[from][via] + distances[via][to];

        if (distanceThroughVia < distances[from][to]) {
          distances[from][to] = distanceThroughVia;
          next[from][to] = next[from][via];
        }
      }
    }
  }

  return matrices;
}

// reconstructs the shortest path between two nodes using the routing matrices generated by the Floyd-Warshall algorithm
export function reconstructPath(fromNodeId, toNodeId, matrices) {
  const fromIndex = matrices.indexByNodeId.get(fromNodeId);
  const toIndex = matrices.indexByNodeId.get(toNodeId);

  if (fromIndex === undefined) {
    throw new TypeError(`Unknown route start node: ${fromNodeId}`);
  }
  if (toIndex === undefined) {
    throw new TypeError(`Unknown route destination node: ${toNodeId}`);
  }
  if (matrices.next[fromIndex][toIndex] === null) {
    return [];
  }

  const path = [fromNodeId];
  let currentIndex = fromIndex;

  while (currentIndex !== toIndex) {
    currentIndex = matrices.next[currentIndex][toIndex];
    path.push(matrices.nodeIds[currentIndex]);
  }

  return path;
}
